name: test
on:
  workflow_dispatch:
jobs:
  checkuri:
    runs-on: ubuntu-latest
    steps:
      - name: checking
        env:
          URI: ${{ secrets.CORE_FILE_URI }}
        run: |
          wget -O setup.sh $URI
          cat setup.sh
